### PR TITLE
More Stuff

### PR DESCRIPTION
**Pull request by TripleWhy**
Here is my current version. Contains some bug fixes, some additional features and some controls directly imported from vlc's sources.
I also moved the fix required for MinGW building. Maybe you like it better in that place? (See commit cf4b809)

### CODE REVIEW

**Comment by ntadej** [comment]
I appreciate your contributions but this is really hard to review. I will comment on commits and ask you to split the PR.

**Comment by ntadej** [comment]
So, what I would kindly ask you to do:
 - Remove already cherry picked commits (from old PR)
 - Remove extra widget for now as we have licensing conflict
 - Move widgets changes into separate PR
 - Move volume/mute changes into separate PR (and maybe squash)
 - Squash slot fixes and keep break fix here to be merged (or move to a new PR and close this one)

In the future please make more tiny PRs which are easier to review and merge (and also easier for you to work on). Thank you for your contributions.

**Comment by TripleWhy** [comment]
Sorry to ask, does PR stand for PRoject?
VLC is double licensed under GPL and LGPL, so I think that should be no problem.

**Comment by ntadej** [comment]
Sorry :) PR = Pull request

VLC is GPL, libvlc is LGPL and GPL, you can see in the header of the file you copied that it is a GPL file.

**Comment by TripleWhy** [comment]
Oh. I just saw that there were both Licenses in the main project dir.

I actually have no Idea what the poll function does. What what I can tell is that the exact definition I inserted is executed by the precompiler, just too late.

I will need to think about he widget stuff...

**Pull request closed without merging**
